url: "https://misozune.github.io/portfolio" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
title: "Misozune Portfolio" # the name of your site, e.g. ACME Corp.
